// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    // Devices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class DeviceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Device>
    {
        public DeviceConfiguration()
            : this("dbo")
        {
        }

        public DeviceConfiguration(string schema)
        {
            ToTable("Devices", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SerialNumber).HasColumnName(@"SerialNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.DeviceToken).HasColumnName(@"DeviceToken").HasColumnType("nvarchar").IsRequired().HasMaxLength(500);
            Property(x => x.DeviceType).HasColumnName(@"DeviceType").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.FlgStatus).HasColumnName(@"FlgStatus").HasColumnType("smallint").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.UserDeviceId).HasColumnName(@"UserDevice_Id").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.UserDevice).WithMany(b => b.Devices).HasForeignKey(c => c.UserDeviceId).WillCascadeOnDelete(false); // FK_dbo.Devices_dbo.UserDevices_UserDevice_Id
        }
    }

}
// </auto-generated>
