// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    // Message
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class MessageConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Message>
    {
        public MessageConfiguration()
            : this("dbo")
        {
        }

        public MessageConfiguration(string schema)
        {
            ToTable("Message", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsRequired();
            Property(x => x.SendingTime).HasColumnName(@"SendingTime").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar").IsRequired().HasMaxLength(500);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsRequired().HasMaxLength(500);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bit").IsOptional();
            Property(x => x.SenderId).HasColumnName(@"SenderId").HasColumnType("int").IsRequired();
            Property(x => x.ReciverId).HasColumnName(@"ReciverId").HasColumnType("int").IsRequired();
            Property(x => x.RequestId).HasColumnName(@"RequestId").HasColumnType("int").IsOptional();
            Property(x => x.OfferId ).HasColumnName(@"OfferId").HasColumnType("int").IsOptional();
            Property(x => x.MessageType).HasColumnName(@"MessageType").HasColumnType("int").IsOptional();
            Property(x => x.FlgStatus).HasColumnName(@"FlgStatus").HasColumnType("smallint").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.Reciver).WithMany(b => b.Reciver).HasForeignKey(c => c.ReciverId).WillCascadeOnDelete(false); // FK_dbo.Message_dbo.User_ReciverId
            HasOptional (a => a.Request).WithMany(b => b.Messages).HasForeignKey(c => c.RequestId).WillCascadeOnDelete(false); // FK_dbo.Message_dbo.Request_RequestId
            HasRequired(a => a.Sender).WithMany(b => b.Sender).HasForeignKey(c => c.SenderId).WillCascadeOnDelete(false); // FK_dbo.Message_dbo.User_SenderId
            HasOptional (a => a.Offer ).WithMany(b => b.Messages).HasForeignKey(c => c.OfferId ).WillCascadeOnDelete(false);
        }
    }

}
// </auto-generated>
