// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    // OfferImages
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class OfferImageConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OfferImage>
    {
        public OfferImageConfiguration()
            : this("dbo")
        {
        }

        public OfferImageConfiguration(string schema)
        {
            ToTable("OfferImages", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.OfferId).HasColumnName(@"OfferId").HasColumnType("int").IsRequired();
            Property(x => x.ImageTitle).HasColumnName(@"ImageTitle").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ImageDescription).HasColumnName(@"ImageDescription").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ImageUrl).HasColumnName(@"ImageUrl").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.FlgStatus).HasColumnName(@"FlgStatus").HasColumnType("smallint").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();

            // Foreign keys
           // HasRequired(a => a.Offer).WithMany(b => b.OfferImages).HasForeignKey(c => c.OfferId); // FK_dbo.OfferImages_dbo.Offer_OfferId
        }
    }

}
// </auto-generated>
