// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl
{

    // OfferDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class OfferDetailConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OfferDetail>
    {
        public OfferDetailConfig()
            : this("dbo")
        {
        }

        public OfferDetailConfig(string schema)
        {
            ToTable("OfferDetails", schema);
            HasKey(x => x.Id);

            Property(x => x.OfferId).HasColumnName(@"OfferId").HasColumnType("int").IsRequired();
            //Property(x => x.AcceptedUserId).HasColumnName(@"AcceptedUserId").HasColumnType("int").IsRequired();
            //Property(x => x.AcceptedDate).HasColumnName(@"AcceptedDate").HasColumnType("datetime").IsOptional();
            //Property(x => x.Notes).HasColumnName(@"Notes").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);

            // Foreign keys
            HasRequired(a => a.Offer).WithMany(b => b.OfferDetails).HasForeignKey(c => c.OfferId).WillCascadeOnDelete(false); // FK_OfferDetails_Offer
            //HasRequired(a => a.User).WithMany(b => b.OfferDetails).HasForeignKey(c => c.AcceptedUserId).WillCascadeOnDelete(false); // FK_OfferDetails_User
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
