// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    // OfferDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class OfferDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OfferDetail>
    {
        public OfferDetailConfiguration()
            : this("dbo")
        {
        }

        public OfferDetailConfiguration(string schema)
        {
            ToTable("OfferDetails", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.OfferId).HasColumnName(@"OfferId").HasColumnType("int").IsRequired();
            Property(x => x.TruckId).HasColumnName(@"TruckId").HasColumnType("int").IsRequired();
            Property(x => x.NumberOfTrucks).HasColumnName(@"NumberOfTrucks").HasColumnType("int").IsRequired();
            Property(x => x.FlgStatus).HasColumnName(@"FlgStatus").HasColumnType("smallint").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.UserId).HasColumnName(@"User_Id").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.User).WithMany(b => b.OfferDetails).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_dbo.OfferDetails_dbo.User_User_Id
            HasRequired(a => a.Offer).WithMany(b => b.OfferDetails).HasForeignKey(c => c.OfferId).WillCascadeOnDelete(false); // FK_dbo.OfferDetails_dbo.Offer_OfferId
            HasRequired(a => a.Truck).WithMany(b => b.OfferDetails).HasForeignKey(c => c.TruckId); // FK_dbo.OfferDetails_dbo.Trucks_TruckId
        }
    }

}
// </auto-generated>
