// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl
{

    // Rating
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class RatingConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Rating>
    {
        public RatingConfig()
            : this("dbo")
        {
        }

        public RatingConfig(string schema)
        {
            ToTable("Rating", schema);
            HasKey(x => x.Id);

            Property(x => x.ServiceProviderId).HasColumnName(@"ServiceProviderId").HasColumnType("int").IsRequired();
            Property(x => x.RatingValue).HasColumnName(@"Rating").HasColumnType("int").IsRequired();
            Property(x => x.ServiceRequestId).HasColumnName(@"ServiceRequestId").HasColumnType("int").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsOptional();
            Property(x => x.RequstId).HasColumnName(@"RequstId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Request).WithMany(b => b.Ratings).HasForeignKey(c => c.RequstId).WillCascadeOnDelete(false); // FK_Rating_Request
            HasRequired(a => a.ServiceProvider).WithMany(b => b.ServiceProvider).HasForeignKey(c => c.ServiceProviderId).WillCascadeOnDelete(false); // FK_Rating_User2
            HasRequired(a => a.ServiceRequest).WithMany(b => b.ServiceRequest).HasForeignKey(c => c.ServiceRequestId).WillCascadeOnDelete(false); // FK_Rating_User3
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
