// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    // Rating
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class RatingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Rating>
    {
        public RatingConfiguration()
            : this("dbo")
        {
        }

        public RatingConfiguration(string schema)
        {
            ToTable("Rating", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ServiceProviderId).HasColumnName(@"ServiceProviderId").HasColumnType("int").IsRequired();
            Property(x => x.RatingValue).HasColumnName(@"RatingValue").HasColumnType("decimal").IsRequired();
            Property(x => x.ServiceRequestId).HasColumnName(@"ServiceRequestId").HasColumnType("int").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsOptional();
            Property(x => x.RequstId).HasColumnName(@"RequstId").HasColumnType("int").IsOptional();
            Property(x => x.FlgStatus).HasColumnName(@"FlgStatus").HasColumnType("smallint").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasOptional(a => a.Request).WithMany(b => b.Ratings).HasForeignKey(c => c.RequstId).WillCascadeOnDelete(false); // FK_dbo.Rating_dbo.Request_RequstId
            HasRequired(a => a.ServiceProvider).WithMany(b => b.ServiceProviderId).HasForeignKey(c => c.ServiceProviderId).WillCascadeOnDelete(false); // FK_dbo.Rating_dbo.User_ServiceProviderId
            HasRequired(a => a.ServiceRequest).WithMany(b => b.ServiceRequest).HasForeignKey(c => c.ServiceRequestId).WillCascadeOnDelete(false); // FK_dbo.Rating_dbo.User_ServiceRequestId
        }
    }

}
// </auto-generated>
