// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    // RequestDetaile
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class RequestDetaileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RequestDetaile>
    {
        public RequestDetaileConfiguration()
            : this("dbo")
        {
        }

        public RequestDetaileConfiguration(string schema)
        {
            ToTable("RequestDetaile", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RequestId).HasColumnName(@"RequestId").HasColumnType("int").IsRequired();
            Property(x => x.TruckId).HasColumnName(@"TruckId").HasColumnType("int").IsRequired();
            Property(x => x.NumberOfTrucks).HasColumnName(@"NumberOfTrucks").HasColumnType("int").IsRequired();
            Property(x => x.FlgStatus).HasColumnName(@"FlgStatus").HasColumnType("smallint").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.Request).WithMany(b => b.RequestDetailes).HasForeignKey(c => c.RequestId).WillCascadeOnDelete(false); // FK_dbo.RequestDetaile_dbo.Request_RequestId
            HasRequired(a => a.Truck).WithMany(b => b.RequestDetailes).HasForeignKey(c => c.TruckId).WillCascadeOnDelete(false); // FK_dbo.RequestDetaile_dbo.Trucks_TruckId
        }
    }

}
// </auto-generated>
