// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    // RequestDetailesPrices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class RequestDetailesPriceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RequestDetailesPrice>
    {
        public RequestDetailesPriceConfiguration()
            : this("dbo")
        {
        }

        public RequestDetailesPriceConfiguration(string schema)
        {
            ToTable("RequestDetailesPrices", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RequestDetaileId).HasColumnName(@"RequestDetaileId").HasColumnType("int").IsRequired();
            Property(x => x.Price).HasColumnName(@"Price").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.ServiceProviderId).HasColumnName(@"ServiceProviderId").HasColumnType("int").IsRequired();
            Property(x => x.FlgStatus).HasColumnName(@"FlgStatus").HasColumnType("smallint").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.RequestDetaile).WithMany(b => b.RequestDetailesPrices).HasForeignKey(c => c.RequestDetaileId); // FK_dbo.RequestDetailesPrices_dbo.RequestDetaile_RequestDetaileId
            HasRequired(a => a.User).WithMany(b => b.RequestDetailesPrices).HasForeignKey(c => c.ServiceProviderId); // FK_dbo.RequestDetailesPrices_dbo.User_ServiceProviderId
        }
    }

}
// </auto-generated>
