// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl
{

    // RequestDetaile
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class RequestDetaileConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RequestDetaile>
    {
        public RequestDetaileConfig()
            : this("dbo")
        {
        }

        public RequestDetaileConfig(string schema)
        {
            ToTable("RequestDetaile", schema);
            HasKey(x => x.Id);

            Property(x => x.RequestId).HasColumnName(@"RequestId").HasColumnType("int").IsRequired();
            Property(x => x.TruckId).HasColumnName(@"TruckId").HasColumnType("int").IsRequired();
            Property(x => x.NumberOfTrucks).HasColumnName(@"NumberOfTrucks").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Request).WithMany(b => b.RequestDetailes).HasForeignKey(c => c.RequestId).WillCascadeOnDelete(false); // FK_RequestDetaile_Request
            HasRequired(a => a.Truck).WithMany(b => b.RequestDetailes).HasForeignKey(c => c.TruckId).WillCascadeOnDelete(false); // FK_RequestDetaile_Trucks
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
