// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    // Trucks
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class TruckConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Truck>
    {
        public TruckConfiguration()
            : this("dbo")
        {
        }

        public TruckConfiguration(string schema)
        {
            ToTable("Trucks", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Weight).HasColumnName(@"Weight").HasColumnType("int").IsOptional();
            Property(x => x.TypeId).HasColumnName(@"TypeId").HasColumnType("int").IsRequired();
            Property(x => x.IsOcuppied).HasColumnName(@"IsOcuppied").HasColumnType("bit").IsOptional();
            Property(x => x.AvialableNo).HasColumnName(@"AvialableNo").HasColumnType("int").IsOptional();
            Property(x => x.Capacity).HasColumnName(@"Capacity").HasColumnType("decimal").IsOptional().HasPrecision(18,6);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.Width).HasColumnName(@"Width").HasColumnType("int").IsOptional();
            Property(x => x.Height).HasColumnName(@"height").HasColumnType("int").IsOptional();
            Property(x => x.ParanetId).HasColumnName(@"ParanetId").HasColumnType("int").IsOptional();
            Property(x => x.TruckImagePath).HasColumnName(@"TruckImagePath").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.TruckImgeName).HasColumnName(@"TruckImgeName").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.FlgStatus).HasColumnName(@"FlgStatus").HasColumnType("smallint").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("int").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasOptional(a => a.Paranet).WithMany(b => b.Trucks).HasForeignKey(c => c.ParanetId).WillCascadeOnDelete(false); // FK_dbo.Trucks_dbo.Trucks_ParanetId
            HasRequired(a => a.TruckType).WithMany(b => b.Trucks).HasForeignKey(c => c.TypeId).WillCascadeOnDelete(false); // FK_dbo.Trucks_dbo.TruckType_TypeId
        }
    }

}
// </auto-generated>
