// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl
{

    // UserDevices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class UserDeviceConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserDevice>
    {
        public UserDeviceConfig()
            : this("dbo")
        {
        }

        public UserDeviceConfig(string schema)
        {
            ToTable("UserDevices", schema);
            HasKey(x => x.Id);

            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsOptional().IsRequired();
            Property(x => x.DeviceId).HasColumnName(@"DeviceId").HasColumnType("int").IsOptional().IsRequired();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
