//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ejab.BAL.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App Arabic Is Required.
        /// </summary>
        public static string AbouAppArabicRequired {
            get {
                return ResourceManager.GetString("AbouAppArabicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App EnglishIs Required.
        /// </summary>
        public static string AbouAppEnglishRequired {
            get {
                return ResourceManager.GetString("AbouAppEnglishRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App Arabic.
        /// </summary>
        public static string AboutAppArb {
            get {
                return ResourceManager.GetString("AboutAppArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App English.
        /// </summary>
        public static string AboutAppEng {
            get {
                return ResourceManager.GetString("AboutAppEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Application.
        /// </summary>
        public static string AboutAppText {
            get {
                return ResourceManager.GetString("AboutAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance .
        /// </summary>
        public static string AcceptedBy {
            get {
                return ResourceManager.GetString("AcceptedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Date.
        /// </summary>
        public static string AcceptedDate {
            get {
                return ResourceManager.GetString("AcceptedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string AddAboutApp {
            get {
                return ResourceManager.GetString("AddAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us Info.
        /// </summary>
        public static string AddContactUs {
            get {
                return ResourceManager.GetString("AddContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Message.
        /// </summary>
        public static string AddMessage {
            get {
                return ResourceManager.GetString("AddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notification.
        /// </summary>
        public static string AddNoty {
            get {
                return ResourceManager.GetString("AddNoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Region.
        /// </summary>
        public static string AddRegion {
            get {
                return ResourceManager.GetString("AddRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Longitude.
        /// </summary>
        public static string AddressLongitude {
            get {
                return ResourceManager.GetString("AddressLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Rules.
        /// </summary>
        public static string AdminRules {
            get {
                return ResourceManager.GetString("AdminRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins Numbers.
        /// </summary>
        public static string AdminsNumbers {
            get {
                return ResourceManager.GetString("AdminsNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Latitude.
        /// </summary>
        public static string AdressLatitude {
            get {
                return ResourceManager.GetString("AdressLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestes.
        /// </summary>
        public static string AllRequestes {
            get {
                return ResourceManager.GetString("AllRequestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllRules {
            get {
                return ResourceManager.GetString("AllRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Providers.
        /// </summary>
        public static string AllServiceProviders {
            get {
                return ResourceManager.GetString("AllServiceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Arabic.
        /// </summary>
        public static string AnswerArabic {
            get {
                return ResourceManager.GetString("AnswerArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer English.
        /// </summary>
        public static string AnswerEnglish {
            get {
                return ResourceManager.GetString("AnswerEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Downloads.
        /// </summary>
        public static string AppDownloadNumbers {
            get {
                return ResourceManager.GetString("AppDownloadNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Facbook Url Is Requird.
        /// </summary>
        public static string AppFacbookUrlRequird {
            get {
                return ResourceManager.GetString("AppFacbookUrlRequird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Link.
        /// </summary>
        public static string AppLink {
            get {
                return ResourceManager.GetString("AppLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Twitter Url Is Requird.
        /// </summary>
        public static string AppTwitterUrlRequird {
            get {
                return ResourceManager.GetString("AppTwitterUrlRequird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Url Is Required.
        /// </summary>
        public static string AppURlRequired {
            get {
                return ResourceManager.GetString("AppURlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Users.
        /// </summary>
        public static string AppUsers {
            get {
                return ResourceManager.GetString("AppUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailableOffers.
        /// </summary>
        public static string AvailableOffers {
            get {
                return ResourceManager.GetString("AvailableOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avialable Rules.
        /// </summary>
        public static string AvialableRules {
            get {
                return ResourceManager.GetString("AvialableRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Detiles  Arabic.
        /// </summary>
        public static string BodyArb {
            get {
                return ResourceManager.GetString("BodyArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Detiles.
        /// </summary>
        public static string BodyEng {
            get {
                return ResourceManager.GetString("BodyEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelDeleting {
            get {
                return ResourceManager.GetString("CancelDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint.
        /// </summary>
        public static string Cause {
            get {
                return ResourceManager.GetString("Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Chang {
            get {
                return ResourceManager.GetString("Chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePassword.
        /// </summary>
        public static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you Sure you Want to delete this?.
        /// </summary>
        public static string CheckDeleting {
            get {
                return ResourceManager.GetString("CheckDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this region already exist.
        /// </summary>
        public static string CheckRegion {
            get {
                return ResourceManager.GetString("CheckRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region name Required.
        /// </summary>
        public static string CheckRegionName {
            get {
                return ResourceManager.GetString("CheckRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no roles  for this user.
        /// </summary>
        public static string CheckUserRoles {
            get {
                return ResourceManager.GetString("CheckUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compaines.
        /// </summary>
        public static string Compaines {
            get {
                return ResourceManager.GetString("Compaines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggesion and complints.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints In Interval.
        /// </summary>
        public static string ComplaintsInInterval {
            get {
                return ResourceManager.GetString("ComplaintsInInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints Numbers.
        /// </summary>
        public static string ComplaintsNumbers {
            get {
                return ResourceManager.GetString("ComplaintsNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComplaintStatus.
        /// </summary>
        public static string ComplaintStatus {
            get {
                return ResourceManager.GetString("ComplaintStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Reyal Saudi).
        /// </summary>
        public static string CurrencySymoble {
            get {
                return ResourceManager.GetString("CurrencySymoble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Count.
        /// </summary>
        public static string CustomersCount {
            get {
                return ResourceManager.GetString("CustomersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day-Month-Year.
        /// </summary>
        public static string DateFormate {
            get {
                return ResourceManager.GetString("DateFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your will not be able to recover this again.
        /// </summary>
        public static string DeletetingMessage {
            get {
                return ResourceManager.GetString("DeletetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Detalies {
            get {
                return ResourceManager.GetString("Detalies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deleting.
        /// </summary>
        public static string Dialogconfirm {
            get {
                return ResourceManager.GetString("Dialogconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit My Profile.
        /// </summary>
        public static string EditMyProfile {
            get {
                return ResourceManager.GetString("EditMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Is Exist.
        /// </summary>
        public static string EmailIsExist {
            get {
                return ResourceManager.GetString("EmailIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please write the email in the correct format)
        ///please write the email in the correct format)
        ///Please write the email in the correct formate.
        /// </summary>
        public static string EmailIsINValid {
            get {
                return ResourceManager.GetString("EmailIsINValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Is Required.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Do Not Exist.
        /// </summary>
        public static string EmailNotExsit {
            get {
                return ResourceManager.GetString("EmailNotExsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email To Subscrip.
        /// </summary>
        public static string EmailToSubscripRequired {
            get {
                return ResourceManager.GetString("EmailToSubscripRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment By Name.
        /// </summary>
        public static string EquipmentByName {
            get {
                return ResourceManager.GetString("EquipmentByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name.
        /// </summary>
        public static string EquipmentName {
            get {
                return ResourceManager.GetString("EquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Equipment.
        /// </summary>
        public static string EquipmentParentName {
            get {
                return ResourceManager.GetString("EquipmentParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments.
        /// </summary>
        public static string Equipments {
            get {
                return ResourceManager.GetString("Equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpireDate.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Dayies.
        /// </summary>
        public static string ExpireDayies {
            get {
                return ResourceManager.GetString("ExpireDayies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Pdf.
        /// </summary>
        public static string ExportToPdf {
            get {
                return ResourceManager.GetString("ExportToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Link.
        /// </summary>
        public static string FaceBookLink {
            get {
                return ResourceManager.GetString("FaceBookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Search Fieldes.
        /// </summary>
        public static string FillSearchFieldes {
            get {
                return ResourceManager.GetString("FillSearchFieldes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName Required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved to egab Company.
        /// </summary>
        public static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string fromDate {
            get {
                return ResourceManager.GetString("fromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing.
        /// </summary>
        public static string Heigh {
            get {
                return ResourceManager.GetString("Heigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items  Info.
        /// </summary>
        public static string IntemInfo {
            get {
                return ResourceManager.GetString("IntemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select user Rules.
        /// </summary>
        public static string InterRules {
            get {
                return ResourceManager.GetString("InterRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InValide Phone Number.
        /// </summary>
        public static string InVaidephone {
            get {
                return ResourceManager.GetString("InVaidephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string InValideData {
            get {
                return ResourceManager.GetString("InValideData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAccepted.
        /// </summary>
        public static string IsAccepted {
            get {
                return ResourceManager.GetString("IsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAdmin.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string IsAreadyAccepted {
            get {
                return ResourceManager.GetString("IsAreadyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Not Accepted.
        /// </summary>
        public static string IsNotAccepted {
            get {
                return ResourceManager.GetString("IsNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string IsRead {
            get {
                return ResourceManager.GetString("IsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Info.
        /// </summary>
        public static string ItemsInfo {
            get {
                return ResourceManager.GetString("ItemsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName Required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location From.
        /// </summary>
        public static string LocationFrom {
            get {
                return ResourceManager.GetString("LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location To.
        /// </summary>
        public static string LocationTo {
            get {
                return ResourceManager.GetString("LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email or password and try agin.
        /// </summary>
        public static string Loginerror {
            get {
                return ResourceManager.GetString("Loginerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Do Not Exist.
        /// </summary>
        public static string MailNotExist {
            get {
                return ResourceManager.GetString("MailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Subsuription.
        /// </summary>
        public static string MailSubsuription {
            get {
                return ResourceManager.GetString("MailSubsuription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Expire Date.
        /// </summary>
        public static string MaxExpireDate {
            get {
                return ResourceManager.GetString("MaxExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Expire Dayies.
        /// </summary>
        public static string MaxExpireDayies {
            get {
                return ResourceManager.GetString("MaxExpireDayies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Users Number.
        /// </summary>
        public static string MaxUsersNumber {
            get {
                return ResourceManager.GetString("MaxUsersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageDescription.
        /// </summary>
        public static string MessageDescription {
            get {
                return ResourceManager.GetString("MessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Message Description.
        /// </summary>
        public static string MessageDescriptionIsRequired {
            get {
                return ResourceManager.GetString("MessageDescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Title.
        /// </summary>
        public static string MessageHeader {
            get {
                return ResourceManager.GetString("MessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageReciver.
        /// </summary>
        public static string MessageReciver {
            get {
                return ResourceManager.GetString("MessageReciver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Reciver Is Required.
        /// </summary>
        public static string MessageReciverIsRequired {
            get {
                return ResourceManager.GetString("MessageReciverIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages Count.
        /// </summary>
        public static string MessagesCount {
            get {
                return ResourceManager.GetString("MessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        public static string MessageStat {
            get {
                return ResourceManager.GetString("MessageStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure .
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Title Is Required.
        /// </summary>
        public static string MessageTitleIsRequired {
            get {
                return ResourceManager.GetString("MessageTitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Must be Less Than 10 Digits.
        /// </summary>
        public static string MobileMinDigitCount {
            get {
                return ResourceManager.GetString("MobileMinDigitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Must be 14 Digit.
        /// </summary>
        public static string mobileNumberMustBe14Digit {
            get {
                return ResourceManager.GetString("mobileNumberMustBe14Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Requests.
        /// </summary>
        public static string NewRequests {
            get {
                return ResourceManager.GetString("NewRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data  Aviable Now.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Address.
        /// </summary>
        public static string NotificationAddress {
            get {
                return ResourceManager.GetString("NotificationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification  Description.
        /// </summary>
        public static string NotificationDescription {
            get {
                return ResourceManager.GetString("NotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications .
        /// </summary>
        public static string NotificationsAndMessages {
            get {
                return ResourceManager.GetString("NotificationsAndMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Seen.
        /// </summary>
        public static string NotSeen {
            get {
                return ResourceManager.GetString("NotSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noty Counts.
        /// </summary>
        public static string NotyCounts {
            get {
                return ResourceManager.GetString("NotyCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NotyTitle {
            get {
                return ResourceManager.GetString("NotyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Date.
        /// </summary>
        public static string OfferDate {
            get {
                return ResourceManager.GetString("OfferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Details.
        /// </summary>
        public static string OfferDetails {
            get {
                return ResourceManager.GetString("OfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Image.
        /// </summary>
        public static string OfferImage {
            get {
                return ResourceManager.GetString("OfferImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Data.
        /// </summary>
        public static string OfferInfo {
            get {
                return ResourceManager.GetString("OfferInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Number.
        /// </summary>
        public static string OfferNumber {
            get {
                return ResourceManager.GetString("OfferNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Numbers.
        /// </summary>
        public static string OfferNumbers {
            get {
                return ResourceManager.GetString("OfferNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers By State.
        /// </summary>
        public static string OffersByState {
            get {
                return ResourceManager.GetString("OffersByState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers In Interval.
        /// </summary>
        public static string OffersInInterval {
            get {
                return ResourceManager.GetString("OffersInInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers In Region.
        /// </summary>
        public static string OffersInRegion {
            get {
                return ResourceManager.GetString("OffersInRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer State.
        /// </summary>
        public static string OfferState {
            get {
                return ResourceManager.GetString("OfferState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string offerTitle {
            get {
                return ResourceManager.GetString("offerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferTrucks.
        /// </summary>
        public static string OfferTrucks {
            get {
                return ResourceManager.GetString("OfferTrucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnProgress.
        /// </summary>
        public static string OnProgress {
            get {
                return ResourceManager.GetString("OnProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Icon.
        /// </summary>
        public static string ParenttruckIcon {
            get {
                return ResourceManager.GetString("ParenttruckIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Is Required.
        /// </summary>
        public static string PasswordIsrequired {
            get {
                return ResourceManager.GetString("PasswordIsrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Date.
        /// </summary>
        public static string PermissionDate {
            get {
                return ResourceManager.GetString("PermissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Is Required.
        /// </summary>
        public static string PhoneIsRequired {
            get {
                return ResourceManager.GetString("PhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Detailes.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfileImgPath {
            get {
                return ResourceManager.GetString("ProfileImgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposales In Interval.
        /// </summary>
        public static string ProposalesInInterval {
            get {
                return ResourceManager.GetString("ProposalesInInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal Price.
        /// </summary>
        public static string ProposalPrice {
            get {
                return ResourceManager.GetString("ProposalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propsal Date.
        /// </summary>
        public static string PropsalDate {
            get {
                return ResourceManager.GetString("PropsalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propsales By State.
        /// </summary>
        public static string PropsalesByState {
            get {
                return ResourceManager.GetString("PropsalesByState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propsal State.
        /// </summary>
        public static string PropsalState {
            get {
                return ResourceManager.GetString("PropsalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Arabic.
        /// </summary>
        public static string QuestionArabic {
            get {
                return ResourceManager.GetString("QuestionArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question English.
        /// </summary>
        public static string QuestionEnglish {
            get {
                return ResourceManager.GetString("QuestionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Numbers.
        /// </summary>
        public static string QuestionNumbers {
            get {
                return ResourceManager.GetString("QuestionNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciver.
        /// </summary>
        public static string Reciver {
            get {
                return ResourceManager.GetString("Reciver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReciverCode.
        /// </summary>
        public static string ReciverCode {
            get {
                return ResourceManager.GetString("ReciverCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Already Exist.
        /// </summary>
        public static string RegionAlreadyExist {
            get {
                return ResourceManager.GetString("RegionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name Reuired.
        /// </summary>
        public static string RegionNamereuired {
            get {
                return ResourceManager.GetString("RegionNamereuired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Required.
        /// </summary>
        public static string RegionRequired {
            get {
                return ResourceManager.GetString("RegionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string Replay {
            get {
                return ResourceManager.GetString("Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string Requestdate {
            get {
                return ResourceManager.GetString("Requestdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request Details.
        /// </summary>
        public static string requestDetails {
            get {
                return ResourceManager.GetString("requestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Info.
        /// </summary>
        public static string RequestInfo {
            get {
                return ResourceManager.GetString("RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Number.
        /// </summary>
        public static string RequestNumber {
            get {
                return ResourceManager.GetString("RequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests By State.
        /// </summary>
        public static string RequestsByState {
            get {
                return ResourceManager.GetString("RequestsByState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests In Interval.
        /// </summary>
        public static string RequestsInInterval {
            get {
                return ResourceManager.GetString("RequestsInInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests In Region.
        /// </summary>
        public static string RequestsInRegion {
            get {
                return ResourceManager.GetString("RequestsInRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Requests.
        /// </summary>
        public static string RequestsNew {
            get {
                return ResourceManager.GetString("RequestsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests Number.
        /// </summary>
        public static string RequestsNumber {
            get {
                return ResourceManager.GetString("RequestsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request State.
        /// </summary>
        public static string RequestState {
            get {
                return ResourceManager.GetString("RequestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Title.
        /// </summary>
        public static string RequestTitle {
            get {
                return ResourceManager.GetString("RequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Person.
        /// </summary>
        public static string ResponsePerson {
            get {
                return ResourceManager.GetString("ResponsePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule  Name English.
        /// </summary>
        public static string RulDescriptionEng {
            get {
                return ResourceManager.GetString("RulDescriptionEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Description.
        /// </summary>
        public static string RuleDescription {
            get {
                return ResourceManager.GetString("RuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        public static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For Customer.
        /// </summary>
        public static string SearchForCustomer {
            get {
                return ResourceManager.GetString("SearchForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For ServiceProvider.
        /// </summary>
        public static string SearchForServiceProvider {
            get {
                return ResourceManager.GetString("SearchForServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        public static string Seen {
            get {
                return ResourceManager.GetString("Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select From List.
        /// </summary>
        public static string SelectFromList {
            get {
                return ResourceManager.GetString("SelectFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Code.
        /// </summary>
        public static string SenderCode {
            get {
                return ResourceManager.GetString("SenderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To.
        /// </summary>
        public static string SendingTo {
            get {
                return ResourceManager.GetString("SendingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider.
        /// </summary>
        public static string ServiceProvider {
            get {
                return ResourceManager.GetString("ServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider Code.
        /// </summary>
        public static string ServiceProviderId {
            get {
                return ResourceManager.GetString("ServiceProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceProvider Rating.
        /// </summary>
        public static string ServiceProviderRating {
            get {
                return ResourceManager.GetString("ServiceProviderRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Providers.
        /// </summary>
        public static string ServiceProviders {
            get {
                return ResourceManager.GetString("ServiceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Providers Count.
        /// </summary>
        public static string ServiceProvidersCount {
            get {
                return ResourceManager.GetString("ServiceProvidersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        public static string StartingDate {
            get {
                return ResourceManager.GetString("StartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Deleted Successfully.
        /// </summary>
        public static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SureToDelete {
            get {
                return ResourceManager.GetString("SureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks For Subscription.
        /// </summary>
        public static string ThanksForSubscription {
            get {
                return ResourceManager.GetString("ThanksForSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Ttle .
        /// </summary>
        public static string TitleArb {
            get {
                return ResourceManager.GetString("TitleArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Title.
        /// </summary>
        public static string TitleEng {
            get {
                return ResourceManager.GetString("TitleEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string toDate {
            get {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck By Name.
        /// </summary>
        public static string TruckByName {
            get {
                return ResourceManager.GetString("TruckByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Icon.
        /// </summary>
        public static string TruckIcon {
            get {
                return ResourceManager.GetString("TruckIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Name.
        /// </summary>
        public static string TruckName {
            get {
                return ResourceManager.GetString("TruckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Name Arabic.
        /// </summary>
        public static string TruckNameArb {
            get {
                return ResourceManager.GetString("TruckNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Name English.
        /// </summary>
        public static string TruckNameEng {
            get {
                return ResourceManager.GetString("TruckNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name IsRequired.
        /// </summary>
        public static string TruckNameEngRequired {
            get {
                return ResourceManager.GetString("TruckNameEngRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Is Required.
        /// </summary>
        public static string TruckNameRequired {
            get {
                return ResourceManager.GetString("TruckNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        public static string TruckParentName {
            get {
                return ResourceManager.GetString("TruckParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name Arb.
        /// </summary>
        public static string TruckParentNameArb {
            get {
                return ResourceManager.GetString("TruckParentNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name Eng.
        /// </summary>
        public static string TruckParentNameEng {
            get {
                return ResourceManager.GetString("TruckParentNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks.
        /// </summary>
        public static string Trucks {
            get {
                return ResourceManager.GetString("Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks Count.
        /// </summary>
        public static string TrucksCount {
            get {
                return ResourceManager.GetString("TrucksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks &amp;Equipments.
        /// </summary>
        public static string TrucksEquipments {
            get {
                return ResourceManager.GetString("TrucksEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks Number.
        /// </summary>
        public static string TrucksNumber {
            get {
                return ResourceManager.GetString("TrucksNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks Offers Number.
        /// </summary>
        public static string TrucksOffersNumber {
            get {
                return ResourceManager.GetString("TrucksOffersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types Count.
        /// </summary>
        public static string TrucksTypesCount {
            get {
                return ResourceManager.GetString("TrucksTypesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Type.
        /// </summary>
        public static string TruckType {
            get {
                return ResourceManager.GetString("TruckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Eng.
        /// </summary>
        public static string TruckTypeNameEng {
            get {
                return ResourceManager.GetString("TruckTypeNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Link.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnRead {
            get {
                return ResourceManager.GetString("UnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name  Is Required.
        /// </summary>
        public static string UserLastNameRequired {
            get {
                return ResourceManager.GetString("UserLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User First Name Is Requred.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserProfile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins Rules.
        /// </summary>
        public static string UserRules {
            get {
                return ResourceManager.GetString("UserRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Count.
        /// </summary>
        public static string UsersCount {
            get {
                return ResourceManager.GetString("UsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users&amp; Vistors.
        /// </summary>
        public static string UsersVistors {
            get {
                return ResourceManager.GetString("UsersVistors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedith.
        /// </summary>
        public static string Wedith {
            get {
                return ResourceManager.GetString("Wedith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        public static string wrongPassword {
            get {
                return ResourceManager.GetString("wrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your File Is Safe.
        /// </summary>
        public static string YourFileSafe {
            get {
                return ResourceManager.GetString("YourFileSafe", resourceCulture);
            }
        }
    }
}
