// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Models;

namespace Ejab.DAl
{

    public interface IEjabContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AcceptOffer> AcceptOffers { get; set; } // AcceptOffers
        System.Data.Entity.DbSet<Device> Devices { get; set; } // Devices
        System.Data.Entity.DbSet<Interest> Interests { get; set; } // Interests
        System.Data.Entity.DbSet<Message> Messages { get; set; } // Message
        System.Data.Entity.DbSet<Offer> Offers { get; set; } // Offer
        System.Data.Entity.DbSet<OfferDetail> OfferDetails { get; set; } // OfferDetails
        System.Data.Entity.DbSet<OfferImage> OfferImages { get; set; } // OfferImages
        System.Data.Entity.DbSet<PredefinedAction> PredefinedActions { get; set; } // PredefinedActions
        System.Data.Entity.DbSet<ProposalPrice> ProposalPrices { get; set; } // proposalPrice
        System.Data.Entity.DbSet<Rating> Ratings { get; set; } // Rating
        System.Data.Entity.DbSet<Request> Requests { get; set; } // Request
        System.Data.Entity.DbSet<RequestDetaile> RequestDetailes { get; set; } // RequestDetaile
        System.Data.Entity.DbSet<RequestDetailesPrice> RequestDetailesPrices { get; set; } // RequestDetailesPrices
        System.Data.Entity.DbSet<ServiceType> ServiceTypes { get; set; } // ServiceType
        System.Data.Entity.DbSet<SuggestionsComplaint> SuggestionsComplaints { get; set; } // SuggestionsComplaint
        System.Data.Entity.DbSet<SysLog> SysLogs { get; set; } // SysLogs
        System.Data.Entity.DbSet<Truck> Trucks { get; set; } // Trucks
        System.Data.Entity.DbSet<TruckType> TruckTypes { get; set; } // TruckType
        System.Data.Entity.DbSet<User> Users { get; set; } // User
        System.Data.Entity.DbSet<UserDevice> UserDevices { get; set; } // UserDevices

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
