// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Common;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ejab.DAl.Models
{

    // AcceptOffers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class AcceptOffer:BaseModel
    {     
        public int OfferId { get; set; } // OfferId
        public int AcceptedUserId { get; set; } // AcceptedUserId
        public System.DateTime AcceptedDate { get; set; } // AcceptedDate
        public string Notes { get; set; } // Notes
        public OfferState OfferState { get; set; }
        // Foreign keys

        /// <summary>
        /// Parent Offer pointed by [AcceptOffers].([OfferId]) (FK_dbo.AcceptOffers_dbo.Offer_OfferId)
        /// </summary>
        public virtual Offer Offer { get; set; } // FK_dbo.AcceptOffers_dbo.Offer_OfferId

        /// <summary>
        /// Parent User pointed by [AcceptOffers].([AcceptedUserId]) (FK_dbo.AcceptOffers_dbo.User_AcceptedUserId)
        [ForeignKey("AcceptedUserId")] 
        public virtual User User { get; set; } // FK_dbo.AcceptOffers_dbo.User_AcceptedUserId
    }

}
// </auto-generated>
