// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using System.ComponentModel.DataAnnotations.Schema;

namespace Ejab.DAl.Models
{

    // Interests
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Interest : BaseModel
    {
       public int UserId { get; set; } // UserId
        public int? TruckId { get; set; } // TruckId
        [ForeignKey("TruckId")]
        public virtual Truck Truck { get; set; }
        public System.DateTime Date { get; set; } // Date
        public string Notes { get; set; } // Notes
        public int? RegionId { get; set; }
        [ForeignKey("RegionId")]
        public virtual Region Region { get; set; }
        // Foreign keys

        /// <summary>
        /// Parent Truck pointed by [Interests].([TruckId]) (FK_dbo.Interests_dbo.Trucks_TruckId)
        /// </summary>
        /// 
        // FK_dbo.Interests_dbo.Trucks_TruckId

        /// <summary>
        /// Parent User pointed by [Interests].([UserId]) (FK_dbo.Interests_dbo.User_UserId)
        /// </summary>
        public virtual User User { get; set; } // FK_dbo.Interests_dbo.User_UserId
    }

}
// </auto-generated>
