// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Common;
using System.ComponentModel.DataAnnotations;

namespace Ejab.DAl.Models
{

    // Message
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Message : BaseModel
    {
        public System.DateTime Date { get; set; } // Date
        public string SendingTime { get; set; } // SendingTime
        [Required(ErrorMessage ="Message title is required")]
        [StringLength(maximumLength:500)]
        public string Title { get; set; } // Title (length: 50)
        public string Description { get; set; } // Description (length: 500)
        public bool? Status { get; set; } // Status
        public int SenderId { get; set; } // SenderId
        public int ReciverId { get; set; } // ReciverId
        public int? RequestId { get; set; } // RequestId
        public int? OfferId { get; set; } // RequestId
        public MessageType MessageType { get; set; } // MessageType
         // Foreign keys

        /// <summary>
        /// Parent Request pointed by [Message].([RequestId]) (FK_dbo.Message_dbo.Request_RequestId)
        /// </summary>
        public virtual Request Request { get; set; } // FK_dbo.Message_dbo.Request_RequestId
        public virtual Offer Offer { get; set; }
        /// <summary>
        /// Parent User pointed by [Message].([ReciverId]) (FK_dbo.Message_dbo.User_ReciverId)
        /// </summary>
        public virtual User Reciver { get; set; } // FK_dbo.Message_dbo.User_ReciverId

        /// <summary>
        /// Parent User pointed by [Message].([SenderId]) (FK_dbo.Message_dbo.User_SenderId)
        /// </summary>
        public virtual User Sender { get; set; } // FK_dbo.Message_dbo.User_SenderId
    }

}
// </auto-generated>
