// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl.Models
{

    // OfferDetails
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class OfferDetail : BaseModel
    {
        public int OfferId { get; set; } // OfferId
        public int TruckId { get; set; } // TruckId
        public int NumberOfTrucks { get; set; } // NumberOfTrucks
        public int? UserId { get; set; } // User_Id

        // Foreign keys

        /// <summary>
        /// Parent Offer pointed by [OfferDetails].([OfferId]) (FK_dbo.OfferDetails_dbo.Offer_OfferId)
        /// </summary>
        public virtual Offer Offer { get; set; } // FK_dbo.OfferDetails_dbo.Offer_OfferId

        /// <summary>
        /// Parent Truck pointed by [OfferDetails].([TruckId]) (FK_dbo.OfferDetails_dbo.Trucks_TruckId)
        /// </summary>
        public virtual Truck Truck { get; set; } // FK_dbo.OfferDetails_dbo.Trucks_TruckId

        /// <summary>
        /// Parent User pointed by [OfferDetails].([UserId]) (FK_dbo.OfferDetails_dbo.User_User_Id)
        /// </summary>
        public virtual User User { get; set; } // FK_dbo.OfferDetails_dbo.User_User_Id
    }

}
// </auto-generated>
