// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl.Models
{

    // OfferImages
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class OfferImage : BaseModel
    {
         public int OfferId { get; set; } // OfferId
        public string ImageTitle { get; set; } // ImageTitle
        public string ImageDescription { get; set; } // ImageDescription
        public string ImageUrl { get; set; } // ImageUrl
       // Foreign keys

        /// <summary>
        /// Parent Offer pointed by [OfferImages].([OfferId]) (FK_dbo.OfferImages_dbo.Offer_OfferId)
        /// </summary>
        public virtual Offer Offer { get; set; } // FK_dbo.OfferImages_dbo.Offer_OfferId
    }

}
// </auto-generated>
