// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl.Models
{

    // PredefinedActions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class PredefinedAction
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public int? CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public short? FlgStatus { get; set; } // FlgStatus

        // Reverse navigation

        /// <summary>
        /// Child SysLogs where [SysLogs].[PredefinedAction_Id] point to this entity (FK_dbo.SysLogs_dbo.PredefinedActions_PredefinedAction_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysLog> SysLogs { get; set; } // SysLogs.FK_dbo.SysLogs_dbo.PredefinedActions_PredefinedAction_Id

        public PredefinedAction()
        {
            SysLogs = new System.Collections.Generic.List<SysLog>();
        }
    }

}
// </auto-generated>
