// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Common;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ejab.DAl.Models
{

    // proposalPrice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class ProposalPrice:BaseModel 
    {
        public int ReqestId { get; set; } // ReqestId
        public System.DateTime Date { get; set; } // Date
        public decimal Price { get; set; } // price
        public int ServiceProviderId { get; set; } // ServiceProviderId
       // public int? AcceptedBy { get; set; } // AcceptedBy
        public bool? IsAccepted { get; set; } // IsAccepted   
        public System.DateTime?  ExpireDate { get; set; }
        public PropsalStat PropsalStatus { get; set; }
   
        public string  Comments { get; set; }

        // Foreign keys

        /// <summary>
        /// Parent Request pointed by [proposalPrice].([ReqestId]) (FK_proposalPrice_Request)
        /// </summary>
        [ForeignKey("ReqestId")]
        public virtual Request Request { get; set; } // FK_proposalPrice_Request

        /// <summary>
        /// Parent User pointed by [proposalPrice].([ServiceProviderId]) (FK_proposalPrice_User)
        /// </summary>
        [ForeignKey("ServiceProviderId")]
        public virtual User ServiceProvider { get; set; } // FK_proposalPrice_User

        /// <summary>
        /// Parent User pointed by [proposalPrice].([AcceptedBy]) (FK_proposalPrice_User1)
        /// </summary>
        //[ForeignKey("AcceptedBy")]
        //public virtual User User_AcceptedBy { get; set; } // FK_proposalPrice_User1
    }

}
// </auto-generated>
