// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using System.ComponentModel.DataAnnotations.Schema;

namespace Ejab.DAl.Models
{

    // Rating
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Rating : BaseModel
    {
         public int ServiceProviderId { get; set; } // ServiceProviderId
        public decimal  RatingValue { get; set; } // Rating
        public int ServiceRequestId { get; set; } // ServiceRequestId
        public string Description { get; set; } // Description (length: 500)
        public System.DateTime? Date { get; set; } // Date
        public int? RequstId { get; set; } // RequstId
         // Foreign keys

        /// <summary>
        /// Parent Request pointed by [Rating].([RequstId]) (FK_dbo.Rating_dbo.Request_RequstId)
        /// </summary>
        public virtual Request Request { get; set; } // FK_dbo.Rating_dbo.Request_RequstId

        /// <summary>
        /// Parent User pointed by [Rating].([ServiceProviderId]) (FK_dbo.Rating_dbo.User_ServiceProviderId)
        /// </summary>
        [ForeignKey("ServiceProviderId")]
        public virtual User ServiceProvider { get; set; } // FK_dbo.Rating_dbo.User_ServiceProviderId

        /// <summary>
        /// Parent User pointed by [Rating].([ServiceRequestId]) (FK_dbo.Rating_dbo.User_ServiceRequestId)
        /// </summary>
        /// 
        [ForeignKey("ServiceRequestId")]
        public virtual User ServiceRequest { get; set; } // FK_dbo.Rating_dbo.User_ServiceRequestId
    }

}
// </auto-generated>
