// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Common;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ejab.DAl.Models
{

    // RequestDetailesPrices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class RequestDetailesPrice : BaseModel
    {
       public int RequestDetaileId { get; set; } // RequestDetaileId
        public decimal Price { get; set; } // Price
        public int ServiceProviderId { get; set; } // ServiceProviderId
        public System.DateTime  ExpireDate { get; set; }       
        public string  Notes { get; set; }


        /// <summary>
        /// Parent RequestDetaile pointed by [RequestDetailesPrices].([RequestDetaileId]) (FK_dbo.RequestDetailesPrices_dbo.RequestDetaile_RequestDetaileId)
        /// </summary>
        public virtual RequestDetaile RequestDetaile { get; set; } // FK_dbo.RequestDetailesPrices_dbo.RequestDetaile_RequestDetaileId

        /// <summary>
        /// Parent User pointed by [RequestDetailesPrices].([ServiceProviderId]) (FK_dbo.RequestDetailesPrices_dbo.User_ServiceProviderId)
        /// </summary>
        /// 
        [ForeignKey("ServiceProviderId")]
        public virtual User User { get; set; } // FK_dbo.RequestDetailesPrices_dbo.User_ServiceProviderId
    }

}
// </auto-generated>
