// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using System.ComponentModel.DataAnnotations.Schema;

namespace Ejab.DAl.Models
{

    // RequestDetaile
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class RequestDetaile : BaseModel
    {
       public int RequestId { get; set; } // RequestId
        public int TruckId { get; set; } // TruckId
        public int NumberOfTrucks { get; set; } // NumberOfTrucks
        public string Notes { get; set; }

        // Reverse navigation

        /// <summary>
        /// Child RequestDetailesPrices where [RequestDetailesPrices].[RequestDetaileId] point to this entity (FK_dbo.RequestDetailesPrices_dbo.RequestDetaile_RequestDetaileId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RequestDetailesPrice> RequestDetailesPrices { get; set; } // RequestDetailesPrices.FK_dbo.RequestDetailesPrices_dbo.RequestDetaile_RequestDetaileId

        // Foreign keys

        /// <summary>
        /// Parent Request pointed by [RequestDetaile].([RequestId]) (FK_dbo.RequestDetaile_dbo.Request_RequestId)
        /// </summary>
        /// 
        [ForeignKey("RequestId")]
        public virtual Request Request { get; set; } // FK_dbo.RequestDetaile_dbo.Request_RequestId
     

        /// <summary>
        /// Parent Truck pointed by [RequestDetaile].([TruckId]) (FK_dbo.RequestDetaile_dbo.Trucks_TruckId)
        /// </summary>
        /// 
        [ForeignKey("TruckId")]
        public virtual Truck Truck { get; set; } // FK_dbo.RequestDetaile_dbo.Trucks_TruckId

        public RequestDetaile()
        {
            RequestDetailesPrices = new System.Collections.Generic.List<RequestDetailesPrice>();
        }
    }

}
// </auto-generated>
