// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl.Models
{

    // ServiceType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class ServiceType : BaseModel
    {
        public string Name { get; set; } // Name (length: 50) 

        // Reverse navigation

        /// <summary>
        /// Child Offers (Many-to-Many) mapped by table [ServiceTypeOffers]
        /// </summary>
       // public virtual System.Collections.Generic.ICollection<Offer> Offers { get; set; } // Many to many mapping
        /// <summary>
        /// Child Requests where [Request].[ServiceTypeId] point to this entity (FK_dbo.Request_dbo.ServiceType_ServiceTypeId)
        /// </summary>
      //  public virtual System.Collections.Generic.ICollection<Request> Requests { get; set; } // Request.FK_dbo.Request_dbo.ServiceType_ServiceTypeId

        public ServiceType()
        {
            //Requests = new System.Collections.Generic.List<Request>();
            //Offers = new System.Collections.Generic.List<Offer>();
        }
    }

}
// </auto-generated>
