// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl.Models
{

    // SysLogs
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class SysLog
    {
        public int Id { get; set; } // Id (Primary key)
        public int? ActionId { get; set; } // ActionId
        public string Description { get; set; } // Description
        public int? CreatedBy { get; set; } // CreatedBy
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public short? FlgStatus { get; set; } // FlgStatus
        public int? PredefinedActionId { get; set; } // PredefinedAction_Id

        // Foreign keys

        /// <summary>
        /// Parent PredefinedAction pointed by [SysLogs].([PredefinedActionId]) (FK_dbo.SysLogs_dbo.PredefinedActions_PredefinedAction_Id)
        /// </summary>
        public virtual PredefinedAction PredefinedAction { get; set; } // FK_dbo.SysLogs_dbo.PredefinedActions_PredefinedAction_Id
    }

}
// </auto-generated>
