// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Ejab.DAl.Models
{

    // Trucks
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Truck : BaseModel
    {
        public string Name { get; set; } // Name (length: 50)
        public string NameArb { get; set; } // Name (length: 50)
        public int? Weight { get; set; } // Weight
        public int TypeId { get; set; } // TypeId
        public bool? IsOcuppied { get; set; } // IsOcuppied
        public int? AvialableNo { get; set; } // AvialableNo
        public decimal? Capacity { get; set; } // Capacity
        public string Description { get; set; } // Description (length: 250)
        public int? Width { get; set; } // Width
        public int? Height { get; set; } // height
        public int? ParanetId { get; set; } // ParanetId
        public string TruckImagePath { get; set; } // TruckImagePath
        public string TruckImgeName { get; set; } // TruckImgeName (length: 100)
        // Reverse navigation

        /// <summary>
        /// Child Interests where [Interests].[TruckId] point to this entity (FK_dbo.Interests_dbo.Trucks_TruckId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Interest> Interests { get; set; } // Interests.FK_dbo.Interests_dbo.Trucks_TruckId
        /// <summary>
        /// Child OfferDetails where [OfferDetails].[TruckId] point to this entity (FK_dbo.OfferDetails_dbo.Trucks_TruckId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<OfferDetail> OfferDetails { get; set; } // OfferDetails.FK_dbo.OfferDetails_dbo.Trucks_TruckId
        /// <summary>
        /// Child RequestDetailes where [RequestDetaile].[TruckId] point to this entity (FK_dbo.RequestDetaile_dbo.Trucks_TruckId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RequestDetaile> RequestDetailes { get; set; } // RequestDetaile.FK_dbo.RequestDetaile_dbo.Trucks_TruckId
        /// <summary>
        /// Child Trucks where [Trucks].[ParanetId] point to this entity (FK_dbo.Trucks_dbo.Trucks_ParanetId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Truck> Trucks { get; set; } // Trucks.FK_dbo.Trucks_dbo.Trucks_ParanetId

        // Foreign keys

        /// <summary>
        /// Parent Truck pointed by [Trucks].([ParanetId]) (FK_dbo.Trucks_dbo.Trucks_ParanetId)
        /// </summary>
        public virtual Truck Paranet { get; set; } // FK_dbo.Trucks_dbo.Trucks_ParanetId

        /// <summary>
        /// Parent TruckType pointed by [Trucks].([TypeId]) (FK_dbo.Trucks_dbo.TruckType_TypeId)
        /// </summary>
        public virtual TruckType TruckType { get; set; } // FK_dbo.Trucks_dbo.TruckType_TypeId

        public Truck()
        {
            Interests = new System.Collections.Generic.List<Interest>();
            OfferDetails = new System.Collections.Generic.List<OfferDetail>();
            RequestDetailes = new System.Collections.Generic.List<RequestDetaile>();
            Trucks = new System.Collections.Generic.List<Truck>();
        }
    }

}
// </auto-generated>
