// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


using Ejab.DAl.Common;
using Ejab.DAl.Models;
using System.Collections.Generic;

namespace Ejab.DAl
{

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class User : BaseModel
    {
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)
        public string Email { get; set; } // Email (length: 50)
        public string Mobile { get; set; } // Mobile (length: 14)
        public string ProfileImgPath { get; set; } // ProfileImgPath
        public string ProfileName { get; set; } // ProfileName
        public RegisteredBy RegisteredBy { get; set; } // RegisteredBy
        public string FaceBookId { get; set; } // FaceBookId (length: 50)
        public string Address { get; set; } // Address (length: 100)
        public CustomerTypes CustomerType { get; set; } // CustomerType
        public string ResponsiblePerson { get; set; } // ResponsiblePerson (length: 50)
        public bool? IsAdmin { get; set; } // IsAdmin
        public decimal? OverAllrating { get; set; } // OverAllrating
        public decimal? AddressLatitude { get; set; } // AddressLatitude
        public decimal? AddressLongitude { get; set; } // AddressLongitude
        public string Password { get; set; } // Password
        public bool IsActive { get; set; }

        // Reverse navigation

        /// <summary>
        /// Child AcceptOffers where [AcceptOffers].[AcceptedUserId] point to this entity (FK_dbo.AcceptOffers_dbo.User_AcceptedUserId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AcceptOffer> AcceptOffers { get; set; } // AcceptOffers.FK_dbo.AcceptOffers_dbo.User_AcceptedUserId
        /// <summary>
        /// Child Interests where [Interests].[UserId] point to this entity (FK_dbo.Interests_dbo.User_UserId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Interest> Interests { get; set; } // Interests.FK_dbo.Interests_dbo.User_UserId
        /// <summary>
        /// Child Messages where [Message].[ReciverId] point to this entity (FK_dbo.Message_dbo.User_ReciverId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Message> Reciver { get; set; } // Message.FK_dbo.Message_dbo.User_ReciverId
        /// <summary>
        /// Child Messages where [Message].[SenderId] point to this entity (FK_dbo.Message_dbo.User_SenderId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Message> Sender { get; set; } // Message.FK_dbo.Message_dbo.User_SenderId
        /// <summary>
        /// Child Offers where [Offer].[UserId] point to this entity (FK_dbo.Offer_dbo.User_UserId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Offer> Offers { get; set; } // Offer.FK_dbo.Offer_dbo.User_UserId
        /// <summary>
        /// Child OfferDetails where [OfferDetails].[User_Id] point to this entity (FK_dbo.OfferDetails_dbo.User_User_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<OfferDetail> OfferDetails { get; set; } // OfferDetails.FK_dbo.OfferDetails_dbo.User_User_Id
        /// <summary>
        /// Child ProposalPrices where [proposalPrice].[AcceptedBy] point to this entity (FK_proposalPrice_User1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProposalPrice> AcceptedBy { get; set; } // proposalPrice.FK_proposalPrice_User1
        /// <summary>
        /// Child ProposalPrices where [proposalPrice].[ServiceProviderId] point to this entity (FK_proposalPrice_User)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProposalPrice> ServiceProvider { get; set; } // proposalPrice.FK_proposalPrice_User
        /// <summary>
        /// Child Ratings where [Rating].[ServiceProviderId] point to this entity (FK_dbo.Rating_dbo.User_ServiceProviderId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Rating> ServiceProviderId { get; set; } // Rating.FK_dbo.Rating_dbo.User_ServiceProviderId
        /// <summary>
        /// Child Ratings where [Rating].[ServiceRequestId] point to this entity (FK_dbo.Rating_dbo.User_ServiceRequestId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Rating> ServiceRequest { get; set; } // Rating.FK_dbo.Rating_dbo.User_ServiceRequestId
        /// <summary>
        /// Child Requests where [Request].[RequesterId] point to this entity (FK_Request_User)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Request> Requests { get; set; } // Request.FK_Request_User
        /// <summary>
        /// Child RequestDetailesPrices where [RequestDetailesPrices].[ServiceProviderId] point to this entity (FK_dbo.RequestDetailesPrices_dbo.User_ServiceProviderId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RequestDetailesPrice> RequestDetailesPrices { get; set; } // RequestDetailesPrices.FK_dbo.RequestDetailesPrices_dbo.User_ServiceProviderId
        /// <summary>
        /// Child SuggestionsComplaints where [SuggestionsComplaint].[Admin] point to this entity (FK_dbo.SuggestionsComplaint_dbo.User_Admin)
        /// </summary>
      
        /// <summary>
        /// Child SuggestionsComplaints where [SuggestionsComplaint].[ComplainUserId] point to this entity (FK_dbo.SuggestionsComplaint_dbo.User_ComplainUserId)
      
        /// Child UserDevices where [UserDevices].[UserId] point to this entity (FK_dbo.UserDevices_dbo.User_UserId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<UserDevice> UserDevices { get; set; } // UserDevices.FK_dbo.UserDevices_dbo.User_UserId
        public virtual System.Collections.Generic.ICollection<Rule > UserRules { get; set; }
        public virtual System.Collections.Generic.ICollection<Notification > NotificationSender { get; set; }
        public virtual System.Collections.Generic.ICollection<Notification> NotificationReciver { get; set; }

        public User()
        {
            AcceptOffers = new System.Collections.Generic.List<AcceptOffer>();
            Interests = new System.Collections.Generic.List<Interest>();
            Reciver = new System.Collections.Generic.List<Message>();
            Sender = new System.Collections.Generic.List<Message>();
            Offers = new System.Collections.Generic.List<Offer>();
            OfferDetails = new System.Collections.Generic.List<OfferDetail>();
            AcceptedBy = new System.Collections.Generic.List<ProposalPrice>();
            ServiceProvider = new System.Collections.Generic.List<ProposalPrice>();
            ServiceProviderId = new System.Collections.Generic.List<Rating>();
            ServiceRequest = new System.Collections.Generic.List<Rating>();
            Requests = new System.Collections.Generic.List<Request>();
            RequestDetailesPrices = new System.Collections.Generic.List<RequestDetailesPrice>();
          
            UserDevices = new System.Collections.Generic.List<UserDevice>();
            UserRules = new System.Collections.Generic.List<Rule>();
            NotificationSender = new HashSet<Notification>();
            NotificationReciver = new HashSet<Notification>();
        }
    }

}
// </auto-generated>
